header: "ClairUI"
#Must be the absolute path
workdir: "/tmp/clair/"
analysis:
  type: local
server:
  host: ""
  port: "18080"
  filepath: "src"
clair:
  protocol: "http"
  host: "localhost"
  port: "6060"
database:
  vendor: "postgres"
  database: "clair"
  host: "localhost"
  port: "5432"
  schema: "ui"
  username: "postgres"
  password: ""