@startuml
skinparam handwritten true
:User: as User
(Add Containers) as (UC1)
(List Containers) as (UC2)

(Maintain Container) as (UC3)
(Update Container) as (UC3a)
(Read Container) as (UC3b)
(Delete Container) as (UC3c)

(Refresh Container Report) as (UC4)
(View Container Report) as (UC5)

User -> (UC1)
User -> (UC2)
User --> (UC3)
User ---> (UC4)
User ---> (UC5)

(UC3) ..> (UC3a) :<<includes>>
(UC3) ..> (UC3b) :<<includes>>
(UC3) ..> (UC3c) :<<includes>>
@enduml