@startuml
skinparam handwritten true
:User: as User
(Add Container Images) as (UC1)
(List Container Images) as (UC2)
(Maintain Docker Registries) as (MDR1)

(Maintain Container Image) as (UC3)
(Update Container Image) as (UC3a)
(Read Container Image) as (UC3b)
(Delete Container Image) as (UC3c)

(Evaluate Container Image) as (UC4)
(View Container Report) as (UC5)

User -> (UC1)
User -> (UC2)
User --> (UC3)
User ---> (UC4)
User ---> (UC5)
User --> (MDR1)

(UC3) ..> (UC3a) :<<includes>>
(UC3) ..> (UC3b) :<<includes>>
(UC3) ..> (UC3c) :<<includes>>
@enduml